### ISSUE TITLE
Waveform 바깥쪽 클릭 시 region 제거하기

### ISSUE THREAD

**Issue by harry2636** [KAIST-CS409/WebAudioEditor#19]
현재 waveform을 한번 클릭해서 region을 만들면 region이 0개인 state로 돌아갈 수가 없음. 화면 밖을 클릭 시 region이 제거되도록 하기.

**Comment by mecatos95d** [comment]
화면 밖 클릭 외에도 Trim 이후에도 Region을 0으로 만들어줘야 할 것 같습니다.
기존 Trim에서도 this.currentRegionInfo.region.remove(); 로 시도하고 있는 것 같은 것 같은데 작동하고 있지 않습니다.
